import QRCode from "qrcode";
import { buildMembershipRecordHtml } from "@/lib/membership-record-document";

export const dynamic = "force-dynamic";

const API_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:4000";

function firstHeaderValue(value: string | null) {
  return value?.split(",")[0]?.trim() || null;
}

function getPublicOrigin(request: Request) {
  const requestUrl = new URL(request.url);
  const forwardedProto = firstHeaderValue(request.headers.get("x-forwarded-proto"));
  const forwardedHost = firstHeaderValue(request.headers.get("x-forwarded-host"));
  const host = firstHeaderValue(request.headers.get("host"));

  if (forwardedProto && forwardedHost) {
    return `${forwardedProto}://${forwardedHost}`;
  }
  if (host) {
    return `${requestUrl.protocol}//${host}`;
  }
  return requestUrl.origin;
}

export async function GET(
  request: Request,
  context: { params: { id: string } }
) {
  const { id } = context.params;
  const url = new URL(`/public/memberships/${id}/export`, API_URL);
  let dataRes: Response;
  try {
    dataRes = await fetch(url.toString(), { cache: "no-store" });
  } catch {
    return new Response("Export service is unavailable", {
      status: 503,
      headers: { "Content-Type": "text/plain; charset=utf-8" },
    });
  }

  if (!dataRes.ok) {
    const message = dataRes.status === 404 ? "Membership not found" : "Failed to load export document";
    return new Response(message, {
      status: dataRes.status,
      headers: { "Content-Type": "text/plain; charset=utf-8" },
    });
  }

  const { membership, zones } = await dataRes.json() as {
    membership: import("@/lib/api").Membership;
    zones: import("@/lib/api").Zone[];
  };

  const requestUrl = new URL(request.url);
  const verificationUrl = new URL(`/members/${id}/export`, getPublicOrigin(request)).toString();
  const qrDataUrl = await QRCode.toDataURL(verificationUrl, {
    width: 180,
    margin: 1,
    color: { dark: "#111827", light: "#ffffff" },
  });

  const autoPrint = requestUrl.searchParams.get("print") === "1";
  const generatedAt = new Date().toLocaleString();
  const systemSignature = [
    "Generated by Civica.lk",
    `Membership No: ${membership.membershipNo}`,
    `Generated At: ${generatedAt}`,
  ].join(" | ");

  const html = buildMembershipRecordHtml({
    membership,
    zones,
    logoUrl: "/document/huda_doc_header.png",
    verificationUrl,
    qrDataUrl,
    systemSignature,
    autoPrint,
  });

  return new Response(html, {
    status: 200,
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Cache-Control": "no-store",
    },
  });
}
