"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowDownCircle, ArrowLeft, ArrowRightLeft, ArrowUpCircle, Building2, ChevronDown, ChevronRight, CircleDollarSign, Landmark, Plus, Undo2, Wallet } from "lucide-react";
import { Header } from "@/components/header";
import { AbstractBg } from "@/components/abstract-bg";
import { Breadcrumb } from "@/components/breadcrumb";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "@/hooks/use-toast";
import { useAuth } from "@/lib/auth-context";
import { api } from "@/lib/api";

type Period = "this_month" | "this_year" | "all_time" | "custom";
type Account = { id: string; name: string; assetSubtype: "cash" | "bank"; bankName?: string | null; accountNumber?: string | null; description?: string | null; isActive: boolean; status: "active" | "closed"; accountTypeLabel: string; openingBalance: number; cashIn: number; cashOut: number; currentBalance: number };
type Activity = { id: string; transactionDate: string; source: string; description: string; amount: number; direction: "in" | "out"; balance: number; status: "posted" | "reversed"; actionedBy: string; receiptNumber?: string | null; reversalReason?: string | null; reversedAt?: string | null; reversedBy?: string | null; linkedReversalReceipt?: string | null; bankingTransactionId?: string | null; canReverse: boolean; openHref?: string | null };
type Detail = { account: Account; summary: { openingBalance: number; cashIn: number; cashOut: number; currentBalance: number }; activity: Activity[] };
const today = () => new Date().toISOString().slice(0, 10);
const firstOfMonth = () => `${today().slice(0, 8)}01`;
const firstOfYear = () => `${today().slice(0, 4)}-01-01`;
const formatRs = (value: number) => new Intl.NumberFormat("en-LK", { style: "currency", currency: "LKR", minimumFractionDigits: 2 }).format(value).replace("LKR", "Rs.");
const dateLabel = (value: string) => new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "2-digit", year: "numeric" }).format(new Date(value));
const periodDates = (period: Period) => period === "this_month" ? { fromDate: firstOfMonth(), toDate: today() } : period === "this_year" ? { fromDate: firstOfYear(), toDate: today() } : { fromDate: "2000-01-01", toDate: today() };

export function BankingWorkspace({ accountId }: { accountId?: string }) {
  const { user, loading } = useAuth();
  const router = useRouter();
  const canManage = user?.role === "admin" || user?.role === "super_user";
  const [period, setPeriod] = useState<Period>("this_year");
  const [fromDate, setFromDate] = useState(firstOfYear());
  const [toDate, setToDate] = useState(today());
  const [overview, setOverview] = useState<{ totals: Detail["summary"]; rows: Account[] } | null>(null);
  const [detail, setDetail] = useState<Detail | null>(null);
  const [search, setSearch] = useState(""); const [type, setType] = useState("all"); const [status, setStatus] = useState("active"); const [sort, setSort] = useState("name_asc");
  const [accounts, setAccounts] = useState<Account[]>([]); const [expanded, setExpanded] = useState<Record<string, boolean>>({});
  const [addOpen, setAddOpen] = useState(false); const [actionOpen, setActionOpen] = useState<"deposit" | "withdrawal" | "cash_transfer" | "bank_transfer" | null>(null); const [reverseTarget, setReverseTarget] = useState<Activity | null>(null); const [submitting, setSubmitting] = useState(false);
  const [accountForm, setAccountForm] = useState({ name: "", assetSubtype: "cash", bankName: "", accountNumber: "", description: "" });
  const [transactionForm, setTransactionForm] = useState({ sourceAccountId: "", destinationAccountId: "", amount: "", transactionDate: today(), description: "", reference: "" });
  const [reverseReason, setReverseReason] = useState("Incorrect Amount"); const [reverseNote, setReverseNote] = useState("");
  const active = detail?.account.status === "active";
  const relevantAccounts = useMemo(() => accounts.filter((account) => account.isActive), [accounts]);

  useEffect(() => { if (!loading && !user) router.replace("/login"); }, [loading, user, router]);
  useEffect(() => { if (user) void loadAccounts(); }, [user]);
  useEffect(() => { if (user) void (accountId ? loadDetail() : loadOverview()); }, [user, accountId, fromDate, toDate, type, status, sort]);
  useEffect(() => { if (!accountId && user) { const timer = setTimeout(() => void loadOverview(), 250); return () => clearTimeout(timer); } }, [search]);
  async function loadAccounts() { try { setAccounts(await api<Account[]>("/accounting/banking/overview", { params: { fromDate: "2000-01-01", toDate: today(), status: "all" } }).then((data: any) => data.rows)); } catch { setAccounts([]); } }
  async function loadOverview() { try { setOverview(await api("/accounting/banking/overview", { params: { fromDate, toDate, q: search, type, status, sort } })); } catch (error) { toast({ variant: "destructive", title: "Unable to load cash and bank accounts", description: error instanceof Error ? error.message : "Please try again" }); } }
  async function loadDetail() { if (!accountId) return; try { setDetail(await api<Detail>(`/accounting/banking/${accountId}`, { params: { fromDate, toDate } })); } catch (error) { toast({ variant: "destructive", title: "Unable to load account", description: error instanceof Error ? error.message : "Please try again" }); } }
  function changePeriod(value: string) { const next = value as Period; setPeriod(next); if (next !== "custom") { const dates = periodDates(next); setFromDate(dates.fromDate); setToDate(dates.toDate); } }
  async function addAccount(event: FormEvent) { event.preventDefault(); setSubmitting(true); try { const account = await api<Account>("/accounting/banking/accounts", { method: "POST", body: JSON.stringify(accountForm) }); setAddOpen(false); toast({ title: "Cash or bank account added", description: account.name }); router.push(`/banking/${account.id}`); } catch (error) { toast({ variant: "destructive", title: "Unable to add account", description: error instanceof Error ? error.message : "Please try again" }); } finally { setSubmitting(false); } }
  function openAction(action: NonNullable<typeof actionOpen>) { if (!detail) return; const source = detail.account.id; setActionOpen(action); setTransactionForm({ sourceAccountId: source, destinationAccountId: "", amount: "", transactionDate: today(), description: "", reference: "" }); }
  async function submitTransaction(event: FormEvent) { event.preventDefault(); if (!actionOpen) return; setSubmitting(true); try { await api("/accounting/banking/transactions", { method: "POST", body: JSON.stringify({ transactionType: actionOpen, ...transactionForm, amount: Number(transactionForm.amount) }) }); setActionOpen(null); toast({ title: "Banking transaction recorded" }); await Promise.all([loadDetail(), loadAccounts()]); } catch (error) { toast({ variant: "destructive", title: "Unable to record transaction", description: error instanceof Error ? error.message : "Please try again" }); } finally { setSubmitting(false); } }
  async function reverseTransaction(event: FormEvent) { event.preventDefault(); if (!reverseTarget?.bankingTransactionId) return; setSubmitting(true); try { await api(`/accounting/banking/transactions/${reverseTarget.bankingTransactionId}/reverse`, { method: "POST", body: JSON.stringify({ reason: reverseReason, note: reverseNote || null }) }); setReverseTarget(null); toast({ title: "Banking transaction reversed" }); await Promise.all([loadDetail(), loadAccounts()]); } catch (error) { toast({ variant: "destructive", title: "Unable to reverse transaction", description: error instanceof Error ? error.message : "Please try again" }); } finally { setSubmitting(false); } }
  async function closeAccount() { if (!detail || !window.confirm("Close this account? It must have a zero balance.")) return; try { await api(`/accounting/banking/${detail.account.id}/close`, { method: "POST" }); toast({ title: "Account closed" }); await loadDetail(); } catch (error) { toast({ variant: "destructive", title: "Cannot close account", description: error instanceof Error ? error.message : "Please try again" }); } }
  if (loading || !user) return null;
  const summary = detail?.summary ?? overview?.totals ?? { openingBalance: 0, cashIn: 0, cashOut: 0, currentBalance: 0 };
  return <div className="relative min-h-screen bg-background"><AbstractBg /><Header /><main className="relative z-10 mx-auto max-w-7xl space-y-6 p-4 md:p-6"><Breadcrumb items={[{ label: "Dashboard", href: "/" }, { label: "Banking", href: "/banking" }, ...(detail ? [{ label: detail.account.name }] : [])]} />
    {detail ? <><div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><Button variant="ghost" size="sm" onClick={() => router.push("/banking")} className="-ml-2 mb-2"><ArrowLeft className="mr-2 h-4 w-4" />Back</Button><h1 className="text-2xl font-semibold">{detail.account.name}</h1><div className="mt-2 flex flex-wrap gap-2 text-sm text-muted-foreground"><span>Account Type: {detail.account.accountTypeLabel}</span>{detail.account.bankName ? <span>Bank: {detail.account.bankName}</span> : null}{detail.account.accountNumber ? <span>Account No: {detail.account.accountNumber}</span> : null}<span className={`rounded px-2 py-0.5 text-xs ${active ? "bg-emerald-100 text-emerald-700" : "bg-slate-100 text-slate-700"}`}>{detail.account.status}</span></div></div><PeriodPicker period={period} fromDate={fromDate} toDate={toDate} onChange={changePeriod} setFrom={setFromDate} setTo={setToDate} /></div>
      <Summary summary={summary} /><div className="flex flex-wrap justify-end gap-2">{detail.account.assetSubtype === "cash" ? <><Button variant="outline" onClick={() => openAction("deposit")} disabled={!canManage || !active}>Deposit</Button><Button variant="outline" onClick={() => openAction("cash_transfer")} disabled={!canManage || !active}>Cash to Cash Transfer</Button></> : <><Button variant="outline" onClick={() => openAction("withdrawal")} disabled={!canManage || !active}>Withdrawal</Button><Button variant="outline" onClick={() => openAction("bank_transfer")} disabled={!canManage || !active}>Bank to Bank Transfer</Button></>}<Button variant="outline" onClick={closeAccount} disabled={!canManage || !active}>Close Account</Button></div>
      <ActivityTable activity={detail.activity} expanded={expanded} setExpanded={setExpanded} onReverse={setReverseTarget} onOpen={(href) => router.push(href)} /></> : <><div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div><h1 className="text-2xl font-semibold">Cash &amp; Bank Accounts</h1><p className="mt-1 text-sm text-muted-foreground">View and manage all cash, bank and petty cash accounts.</p></div><Button disabled={!canManage} onClick={() => setAddOpen(true)}><Plus className="mr-2 h-4 w-4" />Add New Account</Button></div><PeriodPicker period={period} fromDate={fromDate} toDate={toDate} onChange={changePeriod} setFrom={setFromDate} setTo={setToDate} /><Summary summary={summary} /><Card><CardContent className="space-y-4 p-4"><div className="grid gap-3 md:grid-cols-4"><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search accounts..." /><Select value={type} onValueChange={setType}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All Types</SelectItem><SelectItem value="cash">Cash</SelectItem><SelectItem value="bank">Bank</SelectItem></SelectContent></Select><Select value={status} onValueChange={setStatus}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="active">Active</SelectItem><SelectItem value="closed">Closed</SelectItem><SelectItem value="all">All Statuses</SelectItem></SelectContent></Select><Select value={sort} onValueChange={setSort}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="name_asc">Account Name (A-Z)</SelectItem><SelectItem value="balance_desc">Balance (High-Low)</SelectItem><SelectItem value="balance_asc">Balance (Low-High)</SelectItem></SelectContent></Select></div><AccountTable rows={overview?.rows ?? []} onOpen={(id) => router.push(`/banking/${id}`)} /></CardContent></Card></>}
  </main><AddAccountDialog open={addOpen} onOpenChange={setAddOpen} form={accountForm} setForm={setAccountForm} submitting={submitting} onSubmit={addAccount} /><TransactionDialog open={!!actionOpen} action={actionOpen} current={detail?.account} accounts={relevantAccounts} form={transactionForm} setForm={setTransactionForm} submitting={submitting} onOpenChange={(open: boolean) => !open && setActionOpen(null)} onSubmit={submitTransaction} /><ReverseDialog target={reverseTarget} reason={reverseReason} setReason={setReverseReason} note={reverseNote} setNote={setReverseNote} submitting={submitting} onOpenChange={(open: boolean) => !open && setReverseTarget(null)} onSubmit={reverseTransaction} /></div>;
}

function Summary({ summary }: { summary: Detail["summary"] }) { const cards = [[Wallet, "Opening Balance", summary.openingBalance, "text-blue-600 bg-blue-500/10"], [ArrowDownCircle, "Total Cash In", summary.cashIn, "text-emerald-600 bg-emerald-500/10"], [ArrowUpCircle, "Total Cash Out", summary.cashOut, "text-violet-600 bg-violet-500/10"], [CircleDollarSign, "Current Balance", summary.currentBalance, "text-orange-600 bg-orange-500/10"]] as const; return <div className="grid gap-3 md:grid-cols-4">{cards.map(([Icon, label, value, tone]) => <Card key={label}><CardContent className="flex items-center gap-3 p-4"><div className={`flex h-10 w-10 items-center justify-center rounded-xl ${tone.split(" ")[1]}`}><Icon className={`h-5 w-5 ${tone.split(" ")[0]}`} /></div><div><div className="text-xs text-muted-foreground">{label}</div><div className="text-lg font-semibold">{formatRs(value)}</div></div></CardContent></Card>)}</div>; }
function PeriodPicker({ period, fromDate, toDate, onChange, setFrom, setTo }: { period: Period; fromDate: string; toDate: string; onChange: (value: string) => void; setFrom: (value: string) => void; setTo: (value: string) => void }) { return <div className="flex flex-wrap gap-2"><Select value={period} onValueChange={onChange}><SelectTrigger className="w-[190px]"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="this_month">Current Month</SelectItem><SelectItem value="this_year">Current Financial Year</SelectItem><SelectItem value="all_time">All Time</SelectItem><SelectItem value="custom">Custom</SelectItem></SelectContent></Select>{period === "custom" ? <><Input className="w-[145px]" type="date" value={fromDate} onChange={(event) => setFrom(event.target.value)} /><Input className="w-[145px]" type="date" value={toDate} onChange={(event) => setTo(event.target.value)} /></> : null}</div>; }
function AccountTable({ rows, onOpen }: { rows: Account[]; onOpen: (id: string) => void }) { return <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="border-b text-left text-xs text-muted-foreground"><tr><th className="p-3">Account Name</th><th className="p-3">Account Type</th><th className="p-3 text-right">Opening Balance</th><th className="p-3 text-right">Cash In</th><th className="p-3 text-right">Cash Out</th><th className="p-3 text-right">Current Balance</th><th className="p-3">Status</th><th className="p-3" /></tr></thead><tbody>{rows.map((row) => <tr key={row.id} onClick={() => onOpen(row.id)} className="cursor-pointer border-b hover:bg-muted/40"><td className="p-3 font-medium">{row.name}</td><td className="p-3"><span className="rounded bg-blue-50 px-2 py-1 text-xs text-blue-700">{row.accountTypeLabel}</span></td><td className="p-3 text-right">{formatRs(row.openingBalance)}</td><td className="p-3 text-right text-emerald-700">{formatRs(row.cashIn)}</td><td className="p-3 text-right text-violet-700">{formatRs(row.cashOut)}</td><td className="p-3 text-right font-semibold">{formatRs(row.currentBalance)}</td><td className="p-3"><span className={row.status === "active" ? "text-emerald-700" : "text-slate-600"}>{row.status}</span></td><td className="p-3"><ChevronRight className="h-4 w-4" /></td></tr>)}</tbody></table>{!rows.length ? <div className="p-6 text-center text-sm text-muted-foreground">No cash or bank accounts found.</div> : null}</div>; }
function ActivityTable({ activity, expanded, setExpanded, onReverse, onOpen }: { activity: Activity[]; expanded: Record<string, boolean>; setExpanded: (value: Record<string, boolean>) => void; onReverse: (value: Activity) => void; onOpen: (href: string) => void }) { return <Card><CardContent className="p-0"><div className="border-b p-4 font-semibold">Account Activity</div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="border-b text-left text-xs text-muted-foreground"><tr><th className="p-3">Date</th><th className="p-3">Source</th><th className="p-3">Description</th><th className="p-3 text-right">Amount</th><th className="p-3 text-right">Balance</th><th className="p-3">Status</th><th className="p-3 text-right">Action</th></tr></thead><tbody>{activity.map((row) => <ActivityRow key={row.id} row={row} open={!!expanded[row.id]} onToggle={() => setExpanded({ ...expanded, [row.id]: !expanded[row.id] })} onReverse={onReverse} onOpen={onOpen} />)}</tbody></table>{!activity.length ? <div className="p-6 text-center text-sm text-muted-foreground">No activity in this period.</div> : null}</div></CardContent></Card>; }
function ActivityRow({ row, open, onToggle, onReverse, onOpen }: { row: Activity; open: boolean; onToggle: () => void; onReverse: (row: Activity) => void; onOpen: (href: string) => void }) { return <><tr className="border-b"><td className="p-3 whitespace-nowrap">{dateLabel(row.transactionDate)}</td><td className="p-3">{row.source}</td><td className="p-3">{row.description}</td><td className={`p-3 text-right font-medium ${row.direction === "in" ? "text-emerald-700" : "text-violet-700"}`}>{row.direction === "in" ? "+" : "-"} {formatRs(row.amount)}</td><td className="p-3 text-right">{formatRs(row.balance)}</td><td className="p-3"><span className={row.status === "reversed" ? "text-destructive" : "text-emerald-700"}>{row.status}</span></td><td className="p-3"><div className="flex justify-end gap-2">{row.canReverse ? <Button size="sm" variant="outline" onClick={() => onReverse(row)}><Undo2 className="mr-1 h-3.5 w-3.5" />Reverse</Button> : row.openHref ? <Button size="icon" variant="ghost" title="Open record" onClick={() => onOpen(row.openHref!)}><ArrowRightLeft className="h-4 w-4" /></Button> : null}<Button size="icon" variant="ghost" title="View details" onClick={onToggle}><ChevronDown className={`h-4 w-4 transition ${open ? "rotate-180" : ""}`} /></Button></div></td></tr>{open ? <tr className="border-b bg-muted/30"><td colSpan={7} className="p-3"><div className="grid gap-3 text-xs sm:grid-cols-3"><div><span className="text-muted-foreground">Actioned by</span><div className="font-medium">{row.actionedBy}</div></div><div><span className="text-muted-foreground">Receipt no.</span><div className="font-medium">{row.receiptNumber ?? "-"}</div></div>{row.status === "reversed" ? <><div><span className="text-muted-foreground">Reversal reason</span><div className="font-medium">{row.reversalReason ?? "-"}</div></div><div><span className="text-muted-foreground">Reversed on</span><div className="font-medium">{row.reversedAt ? dateLabel(row.reversedAt) : "-"}</div></div><div><span className="text-muted-foreground">Linked reversal receipt</span><div className="font-medium">{row.linkedReversalReceipt ?? "-"}</div></div></> : null}</div></td></tr> : null}</>; }
function AddAccountDialog({ open, onOpenChange, form, setForm, submitting, onSubmit }: any) { return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Add New Account</DialogTitle></DialogHeader><form onSubmit={onSubmit} className="space-y-4"><div><Label>Account Name</Label><Input required value={form.name} placeholder="BOC Account, Ahmed - Cash in Hand" onChange={(e) => setForm({ ...form, name: e.target.value })} /></div><div><Label>Account Type</Label><Select value={form.assetSubtype} onValueChange={(assetSubtype) => setForm({ ...form, assetSubtype })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="cash">Cash</SelectItem><SelectItem value="bank">Bank</SelectItem></SelectContent></Select></div><div><Label>Bank Name (Optional)</Label><Input value={form.bankName} onChange={(e) => setForm({ ...form, bankName: e.target.value })} /></div><div><Label>Account Number (Optional)</Label><Input value={form.accountNumber} onChange={(e) => setForm({ ...form, accountNumber: e.target.value })} /></div><div><Label>Description (Optional)</Label><Textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></div><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button type="submit" disabled={submitting}>Add Account</Button></div></form></DialogContent></Dialog>; }
function TransactionDialog({ open, action, current, accounts, form, setForm, submitting, onOpenChange, onSubmit }: any) { const title = action === "deposit" ? "Deposit" : action === "withdrawal" ? "Withdrawal" : action === "cash_transfer" ? "Cash to Cash Transfer" : "Bank to Bank Transfer"; const sourceType = action === "deposit" ? "cash" : action === "withdrawal" ? "bank" : action === "cash_transfer" ? "cash" : "bank"; const targetType = action === "deposit" ? "bank" : action === "withdrawal" ? "cash" : sourceType; const sourceOptions = accounts.filter((a: Account) => a.assetSubtype === sourceType && a.id !== form.destinationAccountId); const destinationOptions = accounts.filter((a: Account) => a.assetSubtype === targetType && a.id !== form.sourceAccountId); return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>{title}</DialogTitle></DialogHeader><form onSubmit={onSubmit} className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><div><Label>From</Label><Select value={form.sourceAccountId} onValueChange={(sourceAccountId) => setForm({ ...form, sourceAccountId })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{sourceOptions.map((a: Account) => <SelectItem key={a.id} value={a.id}>{a.name}</SelectItem>)}</SelectContent></Select></div><div><Label>To</Label><Select value={form.destinationAccountId} onValueChange={(destinationAccountId) => setForm({ ...form, destinationAccountId })}><SelectTrigger><SelectValue placeholder={`Select ${targetType} account`} /></SelectTrigger><SelectContent>{destinationOptions.map((a: Account) => <SelectItem key={a.id} value={a.id}>{a.name}</SelectItem>)}</SelectContent></Select></div><div><Label>Date</Label><Input required type="date" value={form.transactionDate} onChange={(e) => setForm({ ...form, transactionDate: e.target.value })} /></div><div><Label>Amount</Label><Input required min="0" step="0.01" type="number" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} /></div><div><Label>Reference (Optional)</Label><Input value={form.reference} onChange={(e) => setForm({ ...form, reference: e.target.value })} /></div></div><div><Label>Description (Optional)</Label><Textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></div><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button type="submit" disabled={submitting || !form.destinationAccountId}>{title}</Button></div></form></DialogContent></Dialog>; }
function ReverseDialog({ target, reason, setReason, note, setNote, submitting, onOpenChange, onSubmit }: any) { return <Dialog open={!!target} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Reverse Banking Entry</DialogTitle></DialogHeader><form onSubmit={onSubmit} className="space-y-4"><div className="rounded border bg-muted/30 p-3 text-sm"><div>{target?.description}</div><div className="mt-1 font-semibold">{target ? formatRs(target.amount) : ""}</div></div><div><Label>Reason for Reversal</Label><Select value={reason} onValueChange={setReason}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["Incorrect Amount", "Incorrect Account", "Duplicate Entry", "Entered by Mistake", "Other"].map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></div><div><Label>Notes (Optional)</Label><Textarea value={note} onChange={(e) => setNote(e.target.value)} /></div><p className="text-xs text-muted-foreground">This action is recorded in the audit trail and cannot be undone.</p><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button type="submit" disabled={submitting}>Confirm Reversal</Button></div></form></DialogContent></Dialog>; }
